// Generated by Selenium IDE
const { Builder } = require('selenium-webdriver');
const chrome = require('selenium-webdriver/chrome');

const driver = new Builder()
  .forBrowser('chrome')
  .setChromeOptions(new chrome.Options().addArguments('--disable-gpu'))
  .build();

describe('UC002', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('UC002', async function() {
    await driver.get("http://publicazo.insprak.com/")
    await driver.findElement(By.linkText("Aulas de Teste de Software")).click()
    await driver.findElement(By.css("h1")).click()
    assert(await driver.findElement(By.css("h1")).getText() == "Aulas de Teste de Software")
    await driver.close()
  })
})
